"""
MahaSarthi Portal – Seed data for Maharashtra government schemes.
"""
from app.models.schemas import Scheme

SCHEMES: list[Scheme] = [
    # ── FARMER SCHEMES ──────────────────────────────────────────────────────
    Scheme(
        id="shetkari-samman-nidhi",
        name="PM Kisan Samman Nidhi (Shetkari)",
        name_mr="पीएम किसान सन्मान निधी",
        description="Central government scheme providing ₹6,000/year financial support to eligible farmer families in 3 installments.",
        description_mr="पात्र शेतकरी कुटुंबांना वर्षाला ₹6,000 आर्थिक मदत 3 हप्त्यांमध्ये दिली जाते.",
        eligibility="Small and marginal farmers with landholding up to 2 hectares.",
        eligibility_mr="2 हेक्टरपर्यंत जमीन असलेले लहान व सीमांत शेतकरी.",
        official_link="https://pmkisan.gov.in/",
        category="farmer",
        roles=["farmer"],
        districts=[],
        tags=["आर्थिक मदत", "शेतकरी", "केंद्र सरकार"],
        last_updated="2024-01",
    ),
    Scheme(
        id="karjamaphi",
        name="Maharashtra Shetkari Karjamaphi Yojana",
        name_mr="महाराष्ट्र शेतकरी कर्जमाफी योजना",
        description="Loan waiver scheme for Maharashtra farmers — provides relief on outstanding crop loans up to ₹2 lakh.",
        description_mr="महाराष्ट्र शेतकऱ्यांसाठी कर्जमाफी — ₹2 लाखापर्यंतचे पीककर्ज माफ केले जाते.",
        eligibility="Farmers who availed crop loans from nationalized banks, cooperative banks in Maharashtra.",
        eligibility_mr="राष्ट्रीयीकृत बँका व सहकारी बँकांमधून पीककर्ज घेतलेले शेतकरी.",
        official_link="https://aaplesarkar.mahaonline.gov.in/",
        category="farmer",
        roles=["farmer"],
        districts=[],
        tags=["कर्जमाफी", "शेतकरी", "पीककर्ज"],
        last_updated="2023-06",
    ),
    Scheme(
        id="pik-vima",
        name="Pradhan Mantri Fasal Bima Yojana (Pik Vima)",
        name_mr="प्रधानमंत्री पीक विमा योजना",
        description="Crop insurance scheme providing financial support to farmers suffering crop loss/damage due to unforeseen calamities.",
        description_mr="अनपेक्षित आपत्तींमुळे पीक नुकसान झालेल्या शेतकऱ्यांना आर्थिक मदत.",
        eligibility="All farmers growing notified crops in notified areas. Compulsory for loanee farmers.",
        eligibility_mr="अधिसूचित क्षेत्रात अधिसूचित पिके घेणारे सर्व शेतकरी. कर्जदार शेतकऱ्यांसाठी अनिवार्य.",
        official_link="https://pmfby.gov.in/",
        category="farmer",
        roles=["farmer"],
        districts=[],
        tags=["पीक विमा", "नुकसान भरपाई", "शेतकरी"],
        last_updated="2024-03",
    ),
    Scheme(
        id="magel-tyala-shetkari",
        name="Magel Tyala Shetkari Scheme",
        name_mr="मागेल त्याला शेतकरी योजना",
        description="Maharashtra government scheme providing individual irrigation facilities (drip/sprinkler) to farmers on demand.",
        description_mr="ठिबक/तुषार सिंचन वैयक्तिक सुविधा देणारी महाराष्ट्र शासनाची मागणी-आधारित योजना.",
        eligibility="Farmers in Maharashtra with agricultural land.",
        eligibility_mr="महाराष्ट्रातील शेतजमीन असलेले शेतकरी.",
        official_link="https://krishi.maharashtra.gov.in/",
        category="farmer",
        roles=["farmer"],
        districts=[],
        tags=["सिंचन", "ठिबक", "शेतकरी"],
        last_updated="2023-11",
    ),
    Scheme(
        id="anudaan-yojana",
        name="Krishi Yantra / Anudaan Yojana",
        name_mr="कृषी यंत्र / अनुदान योजना",
        description="Subsidy scheme for purchase of agricultural machinery — tractors, power tillers, harvesters, etc.",
        description_mr="ट्रॅक्टर, पॉवर टिलर, हार्वेस्टर इत्यादी कृषी यंत्र खरेदीसाठी अनुदान.",
        eligibility="SC/ST farmers get up to 50% subsidy; others up to 40%.",
        eligibility_mr="SC/ST शेतकऱ्यांना 50% पर्यंत अनुदान; इतरांना 40% पर्यंत.",
        official_link="https://mahadbt.maharashtra.gov.in/",
        category="farmer",
        roles=["farmer"],
        districts=[],
        tags=["यंत्र अनुदान", "कृषी", "शेतकरी"],
        last_updated="2024-01",
    ),
    Scheme(
        id="namo-shetkari",
        name="Namo Shetkari Maha Samman Nidhi",
        name_mr="नमो शेतकरी महासन्मान निधी",
        description="Maharashtra state scheme giving ₹6,000/year additional to PM-KISAN beneficiaries, totaling ₹12,000/year.",
        description_mr="PM-KISAN लाभार्थ्यांना महाराष्ट्र शासन अतिरिक्त ₹6,000/वर्ष देते — एकूण ₹12,000/वर्ष.",
        eligibility="All PM-KISAN beneficiaries in Maharashtra.",
        eligibility_mr="महाराष्ट्रातील सर्व PM-KISAN लाभार्थी शेतकरी.",
        official_link="https://krishi.maharashtra.gov.in/",
        category="farmer",
        roles=["farmer"],
        districts=[],
        tags=["नमो शेतकरी", "अनुदान", "महाराष्ट्र"],
        last_updated="2023-10",
    ),

    # ── STUDENT SCHEMES ─────────────────────────────────────────────────────
    Scheme(
        id="mahadbt-scholarship",
        name="MahaDBT Scholarship Portal",
        name_mr="महाडीबीटी शिष्यवृत्ती",
        description="Centralized scholarship portal for Maharashtra students — covers Pre-Matric, Post-Matric, and professional courses.",
        description_mr="महाराष्ट्रातील विद्यार्थ्यांसाठी केंद्रीय शिष्यवृत्ती पोर्टल — Pre-Matric, Post-Matric व व्यावसायिक अभ्यासक्रम.",
        eligibility="Maharashtra domicile students; income criteria vary by scheme.",
        eligibility_mr="महाराष्ट्र अधिवास असलेले विद्यार्थी; उत्पन्न निकष योजनेनुसार बदलतात.",
        official_link="https://mahadbt.maharashtra.gov.in/",
        category="student",
        roles=["student"],
        districts=[],
        tags=["शिष्यवृत्ती", "विद्यार्थी", "महाडीबीटी"],
        last_updated="2024-06",
    ),
    Scheme(
        id="swadhar-gruh",
        name="Dr. Babasaheb Ambedkar Swadhar Gruh Yojana",
        name_mr="डॉ. बाबासाहेब आंबेडकर स्वाधार गृह योजना",
        description="Financial assistance for SC/Nav-Buddhist students pursuing 11th-12th and professional courses outside their taluka.",
        description_mr="तालुक्याबाहेर शिक्षण घेणाऱ्या SC/नवबौद्ध विद्यार्थ्यांना आर्थिक सहाय्य.",
        eligibility="SC/Nav-Buddhist students, income < ₹2.5 lakh/year, residing outside taluka.",
        eligibility_mr="SC/नवबौद्ध विद्यार्थी, उत्पन्न < ₹2.5 लाख/वर्ष, तालुक्याबाहेर वास्तव्य.",
        official_link="https://mahadbt.maharashtra.gov.in/",
        category="student",
        roles=["student"],
        districts=[],
        tags=["SC", "विद्यार्थी", "स्वाधार", "वसतीगृह"],
        last_updated="2024-01",
    ),
    Scheme(
        id="rajyasar-scholarship",
        name="Rajyasar Scholarship (State Merit Scholarship)",
        name_mr="राज्यस्तरीय गुणवत्ता शिष्यवृत्ती",
        description="Merit-based scholarship from Maharashtra government for students excelling in 5th and 8th grade.",
        description_mr="5वी व 8वी मध्ये उत्तम गुण मिळवणाऱ्या विद्यार्थ्यांसाठी महाराष्ट्र सरकारची गुणवत्ता शिष्यवृत्ती.",
        eligibility="Students scoring 55%+ in Class 5 / Class 8 state exams.",
        eligibility_mr="5वी/8वी राज्य परीक्षेत 55%+ गुण मिळवलेले विद्यार्थी.",
        official_link="https://scholarships.gov.in/",
        category="student",
        roles=["student"],
        districts=[],
        tags=["गुणवत्ता", "शिष्यवृत्ती", "विद्यार्थी"],
        last_updated="2023-09",
    ),
    Scheme(
        id="eklavya-scholarship",
        name="Eklavya Scholarship (ST Students)",
        name_mr="एकलव्य शिष्यवृत्ती (आदिवासी विद्यार्थी)",
        description="Scholarship for Scheduled Tribe students for higher education up to post-graduation.",
        description_mr="अनुसूचित जमाती विद्यार्थ्यांसाठी पदव्युत्तर शिक्षणापर्यंत शिष्यवृत्ती.",
        eligibility="ST students in Maharashtra, income < ₹2.5 lakh/year.",
        eligibility_mr="महाराष्ट्रातील ST विद्यार्थी, उत्पन्न < ₹2.5 लाख/वर्ष.",
        official_link="https://mahadbt.maharashtra.gov.in/",
        category="student",
        roles=["student"],
        districts=[],
        tags=["ST", "आदिवासी", "शिष्यवृत्ती"],
        last_updated="2023-08",
    ),

    # ── VILLAGE / GRAM PANCHAYAT SCHEMES ───────────────────────────────────
    Scheme(
        id="gram-sadak-yojana",
        name="Pradhan Mantri Gram Sadak Yojana",
        name_mr="प्रधानमंत्री ग्राम सडक योजना",
        description="Rural connectivity scheme providing all-weather road access to unconnected habitations.",
        description_mr="जोडलेले नसलेल्या वस्त्यांना सर्व ऋतूंत उपलब्ध रस्ता जोडणी.",
        eligibility="Villages with population 500+ (250+ in hill/tribal areas).",
        eligibility_mr="500+ लोकसंख्या असलेली गावे (पहाड/आदिवासी क्षेत्रात 250+).",
        official_link="https://pmgsy.nic.in/",
        category="village",
        roles=["general"],
        districts=[],
        tags=["रस्ते", "ग्रामीण", "ग्राम पंचायत"],
        last_updated="2024-02",
    ),
    Scheme(
        id="jal-jeevan-mission",
        name="Jal Jeevan Mission (Har Ghar Jal)",
        name_mr="जल जीवन मिशन (हर घर जल)",
        description="Scheme to provide tap water connection to every rural household by 2024.",
        description_mr="2024 पर्यंत प्रत्येक ग्रामीण घराला नळ जोडणी देण्याची योजना.",
        eligibility="All rural households in Maharashtra.",
        eligibility_mr="महाराष्ट्रातील सर्व ग्रामीण कुटुंबे.",
        official_link="https://jaljeevanmission.gov.in/",
        category="village",
        roles=["general"],
        districts=[],
        tags=["पाणी पुरवठा", "ग्रामीण", "घरोघरी"],
        last_updated="2024-01",
    ),
    Scheme(
        id="svanidhi-yojana",
        name="PM SVANidhi – Street Vendor Scheme",
        name_mr="PM SVANidhi – पथ विक्रेता योजना",
        description="Micro-credit scheme for street vendors affected by COVID-19 — loan of ₹10,000 to ₹50,000.",
        description_mr="COVID-19 मुळे प्रभावित पथ विक्रेत्यांसाठी ₹10,000 ते ₹50,000 कर्ज.",
        eligibility="Street vendors with vending certificate or letter of recommendation.",
        eligibility_mr="विक्री प्रमाणपत्र किंवा शिफारस पत्र असलेले पथ विक्रेते.",
        official_link="https://pmsvanidhi.mohua.gov.in/",
        category="village",
        roles=["general"],
        districts=[],
        tags=["पथ विक्रेता", "कर्ज", "स्वनिधी"],
        last_updated="2024-01",
    ),

    # ── GENERAL / ALL SCHEMES ───────────────────────────────────────────────
    Scheme(
        id="ayushman-bharat",
        name="Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana",
        name_mr="आयुष्मान भारत – महात्मा ज्योतिराव फुले जन आरोग्य योजना",
        description="Health insurance scheme providing coverage up to ₹5 lakh per family per year for secondary and tertiary hospitalization.",
        description_mr="दुय्यम व तृतीयक रुग्णालयासाठी प्रति कुटुंब प्रतिवर्ष ₹5 लाखापर्यंत आरोग्य विमा.",
        eligibility="Economically weaker sections as per SECC data; Maharashtra extends to yellow/orange ration card holders.",
        eligibility_mr="पिवळ्या/केशरी शिधापत्रिका धारक कुटुंबे.",
        official_link="https://jeevandayee.gov.in/",
        category="general",
        roles=["general", "farmer", "student"],
        districts=[],
        tags=["आरोग्य", "विमा", "रुग्णालय"],
        last_updated="2024-03",
    ),
    Scheme(
        id="ujjwala-yojana",
        name="Pradhan Mantri Ujjwala Yojana",
        name_mr="प्रधानमंत्री उज्ज्वला योजना",
        description="LPG connection scheme for women from Below Poverty Line (BPL) households.",
        description_mr="दारिद्र्यरेषेखालील महिलांना LPG जोडणी देणारी योजना.",
        eligibility="Women from BPL households, age 18+.",
        eligibility_mr="दारिद्र्यरेषेखालील घरातील 18+ वयाच्या महिला.",
        official_link="https://www.pmujjwalayojana.com/",
        category="general",
        roles=["general"],
        districts=[],
        tags=["LPG", "महिला", "BPL"],
        last_updated="2023-12",
    ),
    Scheme(
        id="skill-india-maha",
        name="Maharashtra Skill Development (MSSDS)",
        name_mr="महाराष्ट्र कौशल्य विकास योजना",
        description="Free skill training programs for youth in Maharashtra — IT, construction, retail, healthcare sectors.",
        description_mr="IT, बांधकाम, किरकोळ व्यापार, आरोग्य क्षेत्रातील मोफत कौशल्य प्रशिक्षण.",
        eligibility="Maharashtra residents aged 18-35.",
        eligibility_mr="18-35 वयाचे महाराष्ट्रातील रहिवासी.",
        official_link="https://msdc.co.in/",
        category="general",
        roles=["student", "jobseeker"],
        districts=[],
        tags=["कौशल्य", "प्रशिक्षण", "तरुण"],
        last_updated="2024-02",
    ),
    Scheme(
        id="mahila-arthik-vikas",
        name="Mahila Arthik Vikas Mahamandal (MAVIM)",
        name_mr="महिला आर्थिक विकास महामंडळ",
        description="Microfinance and self-help group support for rural and urban women in Maharashtra.",
        description_mr="महाराष्ट्रातील ग्रामीण व शहरी महिलांसाठी सूक्ष्मवित्त व बचत गट सहाय्य.",
        eligibility="Women (18-60 years) in Maharashtra.",
        eligibility_mr="महाराष्ट्रातील 18-60 वयाच्या महिला.",
        official_link="https://mavim.maharashtra.gov.in/",
        category="general",
        roles=["general"],
        districts=[],
        tags=["महिला", "बचत गट", "मायक्रोफायनान्स"],
        last_updated="2023-10",
    ),
]

# Village-wise donation seed data
VILLAGE_DONATIONS: dict[str, list[dict]] = {
    "nashik": [
        {"year": "2023-24", "amount": "₹45,00,000", "scheme": "Jal Jeevan Mission", "description": "15 hamlet water supply connections"},
        {"year": "2022-23", "amount": "₹32,00,000", "scheme": "PMGSY Road", "description": "2.5 km internal road construction"},
        {"year": "2021-22", "amount": "₹18,00,000", "scheme": "Swachh Bharat Abhiyan", "description": "Community toilet blocks"},
    ],
    "pune": [
        {"year": "2023-24", "amount": "₹75,00,000", "scheme": "Smart Village", "description": "Solar streetlights, paving"},
        {"year": "2022-23", "amount": "₹50,00,000", "scheme": "PMGSY Road", "description": "5 km rural road"},
        {"year": "2021-22", "amount": "₹22,00,000", "scheme": "Digital India", "description": "Common Service Centre setup"},
    ],
    "aurangabad": [
        {"year": "2023-24", "amount": "₹40,00,000", "scheme": "Jal Jeevan Mission", "description": "Pipeline infrastructure"},
        {"year": "2022-23", "amount": "₹28,00,000", "scheme": "Agri Infrastructure Fund", "description": "Cold storage unit"},
    ],
    "amravati": [
        {"year": "2023-24", "amount": "₹35,00,000", "scheme": "Irrigation Development", "description": "Check dam construction"},
        {"year": "2022-23", "amount": "₹20,00,000", "scheme": "PMGSY Road", "description": "3 km farm road"},
    ],
    "nagpur": [
        {"year": "2023-24", "amount": "₹60,00,000", "scheme": "Urban Local Infra", "description": "Market yard development"},
        {"year": "2022-23", "amount": "₹45,00,000", "scheme": "Smart Village", "description": "Wi-Fi + CCTV"},
    ],
}
